<?php

namespace Test\Services\Scout\Actions;

use Test\Services\Scout\ScoutTestCase;
use Videouri\Services\Scout\Actions\Search;

/**
 * @package Test\Services\Scout\Actions
 */
class SearchTest extends ScoutTestCase
{
    /**
     * @var Search
     */
    private $search;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->search = new Search();
    }

    /**
     * @return array
     */
    public function listOfWronglyFormattedQueries()
    {
        return [
            [''],   // empty
            ['  '], // spaces
            ['	'] // tab
        ];
    }

    /**
     * @dataProvider listOfWronglyFormattedQueries
     *
     * @param $query
     *
     * @expectedException \Exception
     * @expectedExceptionMessage Search query cannot be empty
     */
    public function testSettingWronglyFormattedQueryThrowsException($query)
    {
        $this->search->setQuery($query);
    }
}
